name: On-push

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run ci:check
      - run: npx prettier --check .

  build:
    needs: check
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: |
            **/build
            !node_modules
